numpy programs

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [ ]:
arr = np.zeros((2,2))
print(arr)

[[0. 0.]
 [0. 0.]]


In [ ]:
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr = np.arange(1,16)
print(arr.reshape(3,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [ ]:
arr = np.array([[1,2,3,4], [4,5,6,7]])
print(arr.shape)
print(arr.size)

(2, 4)
8


In [ ]:
arr = np.linspace(1, 10, 3)
print(arr)

[ 1.   5.5 10. ]


In [ ]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr = np.full((3, 3), 3)
print(arr)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [ ]:
arr = np.array([[1, 2],[4, 5]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.T)

(2, 2)
2
4
int64
[[1 4]
 [2 5]]


In [ ]:

arr = np.array([
    [[3, 2, 1],
     [6, 5, 4]],

    [[9, 8, 7],
     [12, 11, 10]]
])

print(arr)
print(arr.ndim)   # Number of dimensions
print(arr.shape)  # (Layers, Rows, Columns)
print(arr.size)   # Total number of elements
print(arr[1])        # First layer
print(arr[1])        # Second layer
print(arr[1][0])     # Second row of first layer
print(arr[0][1][1])  # Element 9

[[[ 3  2  1]
  [ 6  5  4]]

 [[ 9  8  7]
  [12 11 10]]]
3
(2, 2, 3)
12
[[ 9  8  7]
 [12 11 10]]
[[ 9  8  7]
 [12 11 10]]
[9 8 7]
5


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr.reshape(3, 2)
print(new_arr)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6,7,8,9])
new_arr_1 = np.reshape(arr,(3,3))
print(new_arr_1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr_3d = np.array([1,2,3,4,5,6,7,8])
new_arr_3d = arr_3d.reshape(2,2,2)
print(new_arr_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50,60])
print(arr[1:6])
print(arr[:3])
print(arr[3:])
print(arr[::3])

[20 30 40 50 60]
[10 20 30]
[40 50 60]
[10 40]


In [ ]:
import numpy as np
arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
print(arr[0:1,1:2])
print(arr[2,:])
print(arr[:,1])

[[20]]
[70 80 90]
[20 50 80]


In [ ]:
import numpy as np
arr = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
print(arr[0,:,:])
print(arr[1,1,:])
print(arr[:,:,0])

[[1 2 3]
 [4 5 6]]
[10 11 12]
[[ 1  4]
 [ 7 10]]


In [ ]:
import numpy as np

a = np.array([40,50,60])
b = np.array([2,5,6])
print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)
print("Division:", a/b)
print("Floor Division:", a//b)
print("Modulus:", a%b)
print("Power:", a**2)

Addition: [42 55 66]
Subtraction: [38 45 54]
Multiplication: [ 80 250 360]
Division: [20. 10. 10.]
Floor Division: [20 10 10]
Modulus: [0 0 0]
Power: [1600 2500 3600]


In [ ]:
import numpy as np
# Create a NumPy array
arr = np.array([1, 4, 9, 16, 25])
print("Original Array:", arr)
# Square Root
print("\nSquare Root:", np.sqrt(arr))
# Square
print("Square:", np.square(arr))
# Cube (Power 3)
print("Cube:", np.power(arr, 3))
# Absolute Value
arr2 = np.array([-5, -10, 15, -20, 25])
print("\nAbsolute Value:", np.abs(arr2))
# Exponential (e^x)
print("\nExponential:", np.exp(arr))
# Natural Logarithm
print("\nNatural Log:", np.log(arr))
# Base-10 Logarithm
print("Log Base 10:", np.log10(arr))
# Sine
print("\nSine:", np.sin(arr))
# Cosine
print("Cosine:", np.cos(arr))
# Tangent
print("Tangent:", np.tan(arr))
# Round Values
decimal = np.array([2.34, 4.67, 8.91, 6.28])
print("\nRounded Values:", np.round(decimal))
# Ceiling
print("Ceiling:", np.ceil(decimal))
# Floor
print("Floor:", np.floor(decimal))

Original Array: [ 1  4  9 16 25]

Square Root: [1. 2. 3. 4. 5.]
Square: [  1  16  81 256 625]
Cube: [    1    64   729  4096 15625]

Absolute Value: [ 5 10 15 20 25]

Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]

Natural Log: [0.         1.38629436 2.19722458 2.77258872 3.21887582]
Log Base 10: [0.         0.60205999 0.95424251 1.20411998 1.39794001]

Sine: [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]
Cosine: [ 0.54030231 -0.65364362 -0.91113026 -0.95765948  0.99120281]
Tangent: [ 1.55740772  1.15782128 -0.45231566  0.30063224 -0.13352641]

Rounded Values: [2. 5. 9. 6.]
Ceiling: [3. 5. 9. 7.]
Floor: [2. 4. 8. 6.]


In [ ]:
import numpy as np

# Create a NumPy array
marks = np.array([75, 82, 90, 68, 95, 88, 79])

print("Original Array:", marks)
# Sort
print("Sorted Array:", np.sort(marks))
# Sum
print("\nSum:", np.sum(marks))

# Mean (Average)
print("Mean:", np.mean(marks))

# Median
print("Median:", np.median(marks))

# Maximum Value
print("Maximum:", np.max(marks))

# Minimum Value
print("Minimum:", np.min(marks))

# Range
print("Range:", np.ptp(marks))

# Standard Deviation
print("Standard Deviation:", np.std(marks))

# Variance
print("Variance:", np.var(marks))

# Index of Maximum Value
print("Index of Maximum:", np.argmax(marks))

# Index of Minimum Value
print("Index of Minimum:", np.argmin(marks))

# Percentiles
print("25th Percentile:", np.percentile(marks, 25))
print("50th Percentile:", np.percentile(marks, 50))
print("75th Percentile:", np.percentile(marks, 75))

Original Array: [75 82 90 68 95 88 79]
Sorted Array: [68 75 79 82 88 90 95]

Sum: 577
Mean: 82.42857142857143
Median: 82.0
Maximum: 95
Minimum: 68
Range: 27
Standard Deviation: 8.633111388421788
Variance: 74.53061224489797
Index of Maximum: 4
Index of Minimum: 3
25th Percentile: 77.0
50th Percentile: 82.0
75th Percentile: 89.0


random

In [ ]:
import numpy as np

# Random number
print(np.random.rand())

# Random numbers
print(np.random.rand(5))

# Random integers
print(np.random.randint(1, 11, 5))

# Random choice
subjects = ["DBMS", "Python", "Java", "ML"]
print(np.random.choice(subjects))

# Normal distribution
print(np.random.normal(50, 10, 5))

# Uniform distribution
print(np.random.uniform(10, 20, 5))

# Bernoulli random variable
print(np.random.binomial(1, 0.5))

# Binomial random variable
print(np.random.binomial(10, 0.7))

# Poisson random variable
print(np.random.poisson(4, 5))

# Exponential random variable

print(np.random.exponential(2, 5))

0.3125432240786219
[0.90477701 0.80521696 0.35680942 0.35395733 0.99690167]
[ 3 10  3  1  8]
Java
[51.95763713 48.25142001 76.78692857 41.85003691 47.70977225]
[10.82889906 16.52168195 10.85997327 16.13054003 15.19070715]
0
7
[3 7 1 7 5]
[0.07561261 1.14542195 2.06111064 1.93632319 0.92246445]
